import HdlNode from './HdlNode';
import { Attribute } from '../const';
import { resolveCellDefinition, toInt } from '../../registry';

import type { HdlNodeAttributes, HdlPort } from './HdlNode';
import type { InspectorConfig } from '../types';
import type { CellDefinition, CellParameters, CellPortDefinition, PortSide } from '../../registry/types';

export interface HdlCellAttributes extends HdlNodeAttributes {
    [Attribute.CellType]?: string;
    [Attribute.Parameters]?: CellParameters;
}

/**
 * Base class for cells described in the cell registry.
 * The ports and the inspector are derived from the cell definition.
 */
export default abstract class HdlCell<A extends HdlCellAttributes = HdlCellAttributes> extends HdlNode<A> {

    getCellType(): string {
        return this.get(Attribute.CellType) || '';
    }

    getDefinition(): CellDefinition | null {
        return resolveCellDefinition(this.getCellType());
    }

    getParameters(): CellParameters {
        return this.get(Attribute.Parameters) || {};
    }

    getParameter(name: string, defaultValue = 0): number {
        return toInt(this.getParameters()[name], defaultValue);
    }

    /**
     * The registry port definitions grouped by the node side.
     */
    getSidePorts(side: PortSide): CellPortDefinition[] {
        const definition = this.getDefinition();
        if (!definition) return [];
        return definition.ports.filter(port => getPortSide(port) === side);
    }

    /**
     * Create the port geometry from the registry port definition.
     */
    protected createPort(port: CellPortDefinition, x: number, y: number, extra: Partial<HdlPort> = {}): HdlPort {
        const parameters = this.getParameters();
        return {
            id: port.id,
            direction: port.direction,
            side: getPortSide(port),
            width: port.width(parameters),
            clock: port.clock,
            inverted: port.polarity ? toInt(parameters[port.polarity], 1) === 0 : false,
            x,
            y,
            ...extra
        };
    }

    override getLabelText(): string {
        const name = this.getName();
        // Hide the names generated by Yosys (e.g. `$and$top.v:12$3`)
        if (!name || name.startsWith('$')) return '';
        return name;
    }

    getInspectorConfig(): InspectorConfig {
        const config = super.getInspectorConfig();
        const definition = this.getDefinition();
        const parameterInputs: Record<string, unknown> = {};

        Object.entries(definition?.parameters || {}).forEach(([key, parameter]) => {
            const label = parameter.hint
                ? /* html */`${parameter.label}
                    <div class="field-hint-container">
                        <img class="field-hint-icon" src="assets/icons/hint.svg">
                        <div class="field-hint">${parameter.hint}</div>
                    </div>`
                : parameter.label;
            switch (parameter.type) {
                case 'width':
                    parameterInputs[key] = { type: 'number', label, group: 'parameters', min: 1, max: 256 };
                    break;
                case 'boolean':
                    parameterInputs[key] = {
                        type: 'select-button-group',
                        label,
                        group: 'parameters',
                        options: [{ value: 0, content: 'No' }, { value: 1, content: 'Yes' }]
                    };
                    break;
                case 'polarity':
                    parameterInputs[key] = {
                        type: 'select-button-group',
                        label,
                        group: 'parameters',
                        options: key === 'CLK_POLARITY'
                            ? [{ value: 1, content: 'Rising' }, { value: 0, content: 'Falling' }]
                            : [{ value: 1, content: 'High' }, { value: 0, content: 'Low' }]
                    };
                    break;
                case 'bits':
                    parameterInputs[key] = { type: 'text', label, group: 'parameters' };
                    break;
            }
        });

        return {
            ...config,
            headerText: definition?.name || this.getCellType(),
            headerHint: definition?.description || '',
            headerSymbol: this.getCellType(),
            groups: {
                ...config.groups,
                parameters: {
                    label: 'Parameters',
                    index: 2
                }
            },
            inputs: {
                [Attribute.Name]: {
                    type: 'text',
                    label: 'Name',
                    group: 'general',
                },
                [Attribute.Parameters]: parameterInputs
            }
        };
    }
}

export function getPortSide(port: CellPortDefinition): PortSide {
    return port.side || (port.direction === 'in' ? 'WEST' : 'EAST');
}
